### ISSUE TITLE
Custom Settings

### ISSUE THREAD

**Issue by Blacksmoke16** [Blacksmoke16/athena#25]
Currently the settings defined in `athena.yml` are specific to Athena itself.  It would be helpful for users to define key value pairs, or nested objects in a format that they determine.  

The plan for this would be have Athena define an empty struct with a set name, like `UserSettings` or something.  Then the config file could now look like

```yml
# Config file for Athena.
---
routing:
  cors:
    enabled: false
    strategy: blacklist
    defaults: &defaults
      allow_origin: https://yourdomain.com
      expose_headers: []
      max_age: 0
      allow_credentials: false
      allow_methods: []
      allow_headers: []
    groups: {}
user_settings:
  aws_key: foobar
  api_domain: https://api.myapp.localdev.com
```

This struct could then be reopened to define the properties that should be read from the config.  This allows for type safety, validations, and methods to be defined.  The user settings would, of course, be available within custom handlers as part of the main config object.  Since the user has control over the structure of the `user_settings` object, they could also define additional objects, similar to how Athena itself has `config`, `routing`, and `cors` objects.

```cr
module Athena::Config
  struct UserSettings
    include CrSerializer(YAML)

    # :nodoc:
    def initialize; end

    property aws_key : String
    property api_domain : String
  end
end
```

I could also define a class method on `Athena` module to return specified config object, so that it would be available within controller actions, command line handlers etc. 

```cr
config = Athena.config.user_settings
aws = AWS::Client.new(config.aws_key, ...)
```
